apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ingress.yaml
  # Uncomment after sealing your postgres credentials:
  # - postgres-credentials-sealed.yaml
