apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  # Add lldap-config-sealed.yaml after creating it with kubeseal.