apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # storageClassName: <your-storage-class>  # uncomment if not using default
