apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: apps
spec:
  encryptedData:
    secret-key: AgDILEBDrrppTYeFjba9K14NzoQdkGsJJ24isrXz6+PKoUrDh0Wci+KgqL1VYUWlAVVtlAu8fsR1/bCRky+K+Wd/mkGrS/FxtQDU9uhBLMxU+1WM/DNbfNcwiTS2LnrisJ/+y9Z9ZlfexPCw+mPN+SEOiKEw2q3Pp2a+x0693buQE6gl/81+LxkFxbXzqmOdAmF9LYPYkLqMqQUtHpzOWw0i0ky5NS8T+uDFIlfL6yKgcgBZoeIfWB0PLOnr4O7pHcoPnSQFMtatuZSfhEmkVqDHaW86GjgPaM0yq10dZKAHRXsoYRsdUXDchJCHqXN+8zWqTF5j62dHRBzxFZ1b1IiNFisKcddHTuxvfaY0Ea8yufymLlHhycpfC2N6cAnSbod5l+jMekfb63fNp+QeIfoqqIGFquWcqv1kNaVTdyrKGxGtHy8KQv73t5fJCze/VcRJTL0sPOermfvBLwH1pk0epVQsRAuk2vaQAmYApV40dNVkO0568QbWa6HZo/idllTefuarE+a64HnRTT5eECGplWPOKMpYZ0mk7H2XOhBGL3otBkvSRJtRRbTGKsSGuLmQSdBJNtr7VCxphOgzgkU6kfWWtEUu3z6X8mMQEI7FJ4c6nyFQzP9Ozx4mnpZZXZGnK6Z9SRtv10AkPxpNqD8kxUnvoUosmeHj/T+RzRuaGo42+NixrkuplJmaCAg3OVNpi7Rfrx4p/0U0002JKBIySA2+7FNA8wme/lSMTz2TSPvdjDjA5/PYMMMjFTSMkYFe8xlQDJORlScBbl1kaiF
  template:
    metadata:
      name: searxng-secret
      namespace: apps