apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: apps
spec:
  encryptedData:
    secret-key: AgA+N0cfmqGhrg230zPugYyXG21D+9qZL9OnWhOyspRUXZrVDQMAMZLZg4NeQ9L/zzqjGFiVEoMAYzSrvdT9EC2tZ/NGRzYRFszANOHmh3bAgHN33+QaxGgDuMN0f3aC+wCfTLYe0LSYH5NeVePElqaPnSLxvKrfTArSXaecL8k5jTcG7Ogt2UNGOfZO4DhK1ckF8ZovqHtTv0uqt5+8BWWC9ELeTCckhiOjOqwrGoqQarda7Tv23Di+1HxlKVZKCKJi1QJwrLKJAhjdMwDcc5TAKJWt847c32x82YYOa9nAGjxXHNoPI1fAdxPh0FSmBAfMYOtbwawtgU7mPGWERpeMD79jP1TqsMiUXvFphcl1mUkV1KCzNZVMwf3dFgRUohF1R1T+Mrh7FHMbwPGYLJZmSh+P0kCMcuwYzvM71GBnAl/NTRkPbIbSwWj0kevrL13I/00/jv4WKkAoaUgE7N0/b8wNeDPShQ7P9/fl8XnP59rPiWVAHu5RCOc3IzXMW59rlyFaTNYQkNal/IO2dPxvwxlDbe+LPpao+Mptzji3Ginq+bEfWPQSNDllUx6SETwPiVQhe+B/ub7tWmmxDGSiXUEAA+WOSsByxyYccarD4uxn4U7S4xlqQs0O6wY2h0h586bYsyKDfZc7GxoK2tmDnM0Dm1TNkHnyTf9mpKBq5fuN5ZF9mHyt/WR83pzNPPTKav4ROVNdD2a5IRjxd9m8mxaZmiCiv+krHXpMyH6K6cuqPkkkT/1ZCr+lnQeFHYF1/HAMQqk8mJ/z6Bz4O5dg
  template:
    metadata:
      name: searxng-secret
      namespace: apps