apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 10Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
