apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik
  - cert-manager
  - sealedsecrets
  - cloudnative-pg
  - helm-repositories.yaml
  - bitnami-helm-repository.yaml
  - immich-helm-repository.yaml
  - postgres-helm-release.yaml
  - redis-helm-release.yaml
