apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik/kustomization.yaml
  - cert-manager/kustomization.yaml
  - sealedsecrets/kustomization.yaml
  - helm-repositories.yaml
  - bitnami-helm-repository.yaml
  - postgres-helm-release.yaml
