apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: invidious-db
  namespace: apps
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  bootstrap:
    initdb:
      database: invidious
      owner: invidious
  storage:
    size: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
