apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: apps
data:
  config.yml: |
    tunnel: 9f5d5385-8f9e-4eda-be94-5b97bac241f4
    credentials-file: /etc/cloudflared/creds.json
    ingress:
      - hostname: n8n.example.com
        service: http://n8n.apps.svc.cluster.local:5678
      - service: http_status:404
