apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: apps
data:
  config.yml: |
    tunnel: 00000000-0000-4000-8000-000000000000
    credentials-file: /etc/cloudflared/creds.json
    ingress:
      - hostname: n8n.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: n8n.example.com
        service: http://n8n.apps.svc.cluster.local:5678
      - hostname: rancher.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: rancher.example.com
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: immich.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: immich.example.com
        service: http://immich-server.apps.svc.cluster.local:2283
      - hostname: nextcloud.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: nextcloud.example.com
        service: http://nextcloud.apps.svc.cluster.local:8080
      - hostname: backroom.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: backroom.example.com
        service: http://nextcloud.apps.svc.cluster.local:8080
      - hostname: lldap.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: lldap.example.com
        service: http://lldap.lldap.svc.cluster.local:17170
      - hostname: jellyfin.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: jellyfin.example.com
        service: http://jellyfin.apps.svc.cluster.local:8096
      - hostname: vault.example.com
        service: http://bitwarden.apps.svc.cluster.local:8080
      - hostname: rss.example.com
        service: http://freshrss.apps.svc.cluster.local:80
      - hostname: music.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: music.example.com
        service: http://navidrome.apps.svc.cluster.local:4533
      - hostname: downloads.example.com
        path: /.well-known/acme-challenge/*
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: downloads.example.com
        service: http://qbittorrent.apps.svc.cluster.local:8080
      - hostname: search.example.com
        service: http://searxng.apps.svc.cluster.local:8080
      - service: http_status:404
