apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: apps
data:
  config.yml: |
    tunnel: 00000000-0000-4000-8000-000000000000
    credentials-file: /etc/cloudflared/creds.json
    ingress:
      - hostname: n8n.example.com
        service: http://n8n.apps.svc.cluster.local:5678
      - hostname: rancher.example.com
        service: http://traefik.traefik.svc.cluster.local:80
      - hostname: immich.example.com
        service: http://immich-server.apps.svc.cluster.local:2283
      - service: http_status:404

